### ISSUE TITLE
error creating 10.15.7 build (both versions)

### ISSUE THREAD

**Issue by gadgetvirtuoso** [munki/macadmin-scripts#76] opened 2020-10-27 20:33 UTC
Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.RmrEL6
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “InstallESDDmg.pkg”.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/001-57224.English.dist', u'-target', '/private/tmp/dmg.RmrEL6']' returned non-zero exit status 1
Product installation failed.

**Comment by gregneagle** [comment] 2020-10-27 20:35
Is your issue this? https://github.com/munki/macadmin-scripts#important-note-for-catalina

**Comment by gregneagle** [comment] 2020-10-27 20:43
Works as expected here:
```
Downloading https://swdist.apple.com/content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/RecoveryHDMetaDmg.pkm...
Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.1QTrj7
installer: The install was successful.
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Users/Shared/macadmin-scripts-main/Install_macOS_10.15.7-19H4.sparseimage
Making read-only compressed disk image containing Install macOS Catalina.app...
..........................................................................................................................................................
created: /Users/Shared/macadmin-scripts-main/Install_macOS_10.15.7-19H4.dmg
Disk image created at: ./Install_macOS_10.15.7-19H4.dmg
```

**Comment by gregneagle** [comment] 2020-10-28 15:38
Closing this on the guess that I'm right about the cause. Please reopen with additional information if that's not the case.

**Closed by gregneagle** 2020-10-28 15:38 UTC
