### ISSUE TITLE
Broken on sonoma, always getting a could not replicate error.

### ISSUE THREAD

**Issue by ldx1u** [munki/macadmin-scripts#123] opened 2023-11-04 06:12 UTC
Whenever i try an installation, it gives me a Could Not Replicate error with some other garbled text. It worked for me about a month ago, tried restarting and i tried the python script aswell.
![image](https://github.com/munki/macadmin-scripts/assets/114127384/6ee47178-1c50-41a5-9936-e19a6f8ddc10)

**Comment by gregneagle** [comment] 2023-11-11 00:12
Not seeing any "garbled text" in your screenshot. Looks like a transfer failure, which can be caused by any number of things external to the script itself.

I successfully used it today on a 14.1.1 machine to download the 14.1.1 installer:
```
31      042-89627     14.1.1    23B81  2023-11-07  macOS Sonoma
32      042-95459     13.6.2   22G320  2023-11-07  macOS Ventura
33      042-95491     13.6.2  22G2321  2023-11-07  macOS Ventura
34      042-95558     14.1.1  23B2082  2023-11-07  macOS Sonoma

Choose a product to download (1-34): 31
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/UpdateBrain.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3611k  100 3611k    0     0  3850k      0 --:--:-- --:--:-- --:--:-- 3870k
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/InstallInfo.plist...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   181  100   181    0     0   1803      0 --:--:-- --:--:-- --:--:--  1925
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/InstallAssistant.pkg...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.0G  100 12.0G    0     0  23.3M      0  0:08:46  0:08:46 --:--:-- 28.0M
Downloading https://swdist.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/InstallAssistant.pkm...
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/MajorOSInfo.pkg...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1376k  100 1376k    0     0  4307k      0 --:--:-- --:--:-- --:--:-- 4370k
Downloading https://swdist.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/MajorOSInfo.pkm...
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/Info.plist...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5129  100  5129    0     0  53466      0 --:--:-- --:--:-- --:--:-- 56362
Downloading https://swcdn.apple.com/content/downloads/60/20/042-89627-A_RWU23DC18G/pbu61ypeudiyidrdq5mpbj0yqmtxcqyjkd/BuildManifest.plist...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7257k  100 7257k    0     0  15.6M      0 --:--:-- --:--:-- --:--:-- 15.8M
Making empty sparseimage...
installer: Package name is macOS Sonoma
installer: Installing at base path /private/tmp/dmg.AWjNgY
installer: The install was successful.
```
So it appears to be something in your specific environment interfering with downloads. curl error code 18 denotes "Partial file. Only a part of the file was transferred."

**Closed** 2023-11-20 16:13 UTC
