### ISSUE TITLE
Failure building 10.15.1 image under High Sierra 10.13.6

### ISSUE THREAD

**Issue by jelockwood** [munki/macadmin-scripts#33] opened 2019-10-31 14:54 UTC
Clearly High Sierra is now a significantly older version of macOS but it was able to successfully run the current installinstallmacos.py script to successfully download Catalina 10.15

However with the recently released 10.15.1 I now get the following errors.

```
Downloading https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/MajorOSInfo.pkm...
Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.pephRb
2019-10-31 14:48:55.000 installer[63099:18468492] Package /Users/Shared/DeployStudio/Files/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/RecoveryHDMetaDmg.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: The install failed (The Installer could not install the software because there was no software found to install.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist', u'-target', '/private/tmp/dmg.pephRb']' returned non-zero exit status 1
Product installation failed.
```

I am currently running the same script on a different Mac under Catalina 10.15 itself and it appears to be succeeding.

If it is not possible to 'fix' the script so it continues to work under High Sierra then we will have to live with this but it would be worth noting this in the readme and/or comments.

**Comment by gregneagle** [comment] 2019-11-03 16:42
I don't test every possible combination of "host" OS and retrieved OS. I might find time to confirm your findings, and if I do, I could add that bit into the README.

I assume you removed the local contents cache and tried again to eliminate the possibility of a bad local download?

There would really be nothing that could be done to "fix" it: all the script does is download the packages and attempt to use Apple's installer to install them. If the installer refuses, there's not much the script can (or really should) do about that.

**Comment by fred** [comment] 2019-11-12 08:49
I Also got the same issue on MacOS 10.14.6 

```
Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.QGGbZB
2019-11-12 15:46:33.549 installer[45576:5810160] Package /Users/fred/rails/macadmin-scripts/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallESDDmg.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: The install failed (The Installer could not install the software because there was no software found to install.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist', u'-target', '/private/tmp/dmg.QGGbZB']' returned non-zero exit status 1
Product installation failed.
```

**Comment by GermanGorbachov** [comment] 2019-11-12 13:47
Under macOS Sierra 10.12.6 the issue is almost the same but the output is slightly different:

`Downloading https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/MajorOSInfo.pkm...
Making empty sparseimage...
installer: Error - ERROR_81E7757A4E
Command '[u'/usr/sbin/installer', u'-pkg', u'/Volumes/LIB_[1Tb]/OS_X_Archive/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist', u'-target', '/private/tmp/dmg.0M3v4z']' returned non-zero exit status 1
Product installation failed.
`

**Comment by gregneagle** [comment] 2019-11-18 19:20
@fred your issue is almost certainly an incomplete or corrupted download of `/Users/fred/rails/macadmin-scripts/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallESDDmg.pkg`. Remove it and try again.

**Comment by gregneagle** [comment] 2019-11-18 19:21
I think @jelockwood's issue may be similar.

**Comment by GermanGorbachov** [comment] 2019-11-18 19:32
I've recently successfully ran the script and created Catalina X.15.1 installer under Sierra X.12.6, so the errors are definitely not about "too old macOS version". It's even possible to successfully use the script on an "incompatible" Mac just by tweaking one of the downloaded files...

**Comment by gregneagle** [comment] 2019-11-18 20:11
I'm going to close this.

**Closed by gregneagle** 2019-11-18 20:11 UTC
